//! Runtime-neutral contracts shared by Mahayana hosts and platform services.

mod canonical_json;
mod commerce;
mod extension_manifest;
mod identity;
mod miniapp_identity;
mod payment;
mod payment_infra;
mod secrets;
mod usage;

pub use canonical_json::canonical_json_bytes;
pub use canonical_json::canonical_json_sha256;
pub use commerce::Currency;
pub use commerce::Entitlement;
pub use commerce::EntitlementStatus;
pub use commerce::JournalEntry;
pub use commerce::JournalLine;
pub use commerce::LedgerError;
pub use commerce::PurchaseRequest;
pub use commerce::Quote;
pub use extension_manifest::CliRuntimeDeclaration;
pub use extension_manifest::CommandDeclaration;
pub use extension_manifest::EntitlementGate;
pub use extension_manifest::HostPermission;
pub use extension_manifest::MahayanaPluginManifest;
pub use extension_manifest::ManifestError;
pub use extension_manifest::MiniAppDeclaration;
pub use extension_manifest::PluginRuntimeDeclaration;
pub use extension_manifest::WasmRuntimeDeclaration;
pub use identity::AccountAccessTokenClaims;
pub use identity::DelegatedTokenRequest;
pub use identity::HostPlatform;
pub use identity::PluginAccessTokenClaims;
pub use identity::PluginContext;
pub use identity::ProfileSummary;
pub use miniapp_identity::MiniAppIdentityError;
pub use miniapp_identity::canonical_repository_source;
pub use miniapp_identity::legacy_official_conversation_id;
pub use miniapp_identity::plugin_instance_id;
pub use payment::CREDITS_CURRENCY;
pub use payment::CreatePaymentIntent;
pub use payment::Money;
pub use payment::PayEngine;
pub use payment::PayError;
pub use payment::PaymentCurrency;
pub use payment::PaymentIntent;
pub use payment::PaymentLedgerEntry;
pub use payment::PaymentLedgerLine;
pub use payment::PaymentMutation;
pub use payment::PaymentRail;
pub use payment::PaymentStatus;
pub use payment::ProductKind;
pub use payment::ProviderOutcome;
pub use payment::RefundRequest;
pub use payment::SettlementRelease;
pub use payment_infra::CreditsLedger;
pub use payment_infra::DeveloperPayout;
pub use payment_infra::MiniAppCheckoutContext;
pub use payment_infra::PaymentCatalog;
pub use payment_infra::PaymentInfrastructureError;
pub use payment_infra::PaymentProviderAdapter;
pub use payment_infra::PaymentRepository;
pub use payment_infra::PayoutStatus;
pub use payment_infra::SettlementPolicy;
pub use payment_infra::SignedProviderCallback;
pub use payment_infra::TrustedCatalogProduct;
pub use payment_infra::VerifiedProviderEvent;
pub use payment_infra::resolve_trusted_payment_intent;
pub use secrets::SecretKey;
pub use secrets::SecretListEntry;
pub use secrets::SecretName;
pub use secrets::SecretNamespace;
pub use secrets::SecretScope;
pub use secrets::SecretStore;
pub use secrets::SecretStoreError;
pub use secrets::SecretValue;
pub use usage::AccountUsageStatus;
pub use usage::UsageCaptureRequest;
pub use usage::UsageReservation;
pub use usage::UsageReservationRequest;
