#[cfg(feature = "full")]
pub mod auth;
#[cfg(feature = "full")]
pub mod auth_env_telemetry;
#[cfg(feature = "full")]
pub mod token_data;
#[cfg(not(feature = "full"))]
#[path = "jwt_expiration.rs"]
pub mod token_data;

#[cfg(feature = "full")]
mod device_code_auth;
#[cfg(feature = "full")]
mod outbound_proxy;
#[cfg(feature = "full")]
mod pkce;
#[cfg(feature = "full")]
mod server;
#[cfg(feature = "full")]
mod success_page;

#[cfg(feature = "full")]
pub use codex_config::types::AuthCredentialsStoreMode;
#[cfg(feature = "full")]
pub use codex_http_client::BuildCustomCaTransportError as BuildLoginHttpClientError;
#[cfg(feature = "full")]
pub use device_code_auth::DeviceCode;
#[cfg(feature = "full")]
pub use device_code_auth::complete_device_code_login;
#[cfg(feature = "full")]
pub use device_code_auth::request_device_code;
#[cfg(feature = "full")]
pub use device_code_auth::run_device_code_login;
#[cfg(feature = "full")]
pub use server::LoginServer;
#[cfg(feature = "full")]
pub use server::ServerOptions;
#[cfg(feature = "full")]
pub use server::ShutdownHandle;
#[cfg(feature = "full")]
pub use server::run_login_server;
#[cfg(feature = "full")]
pub use success_page::CODEX_OPEN_APP_URL;
#[cfg(feature = "full")]
pub use success_page::LoginSuccessPage;
#[cfg(feature = "full")]
pub use success_page::LoginSuccessPageBrand;

#[cfg(feature = "full")]
pub use auth::AgentIdentityAuthPolicy;
#[cfg(feature = "full")]
pub use auth::AuthConfig;
#[cfg(feature = "full")]
pub use auth::AuthDotJson;
#[cfg(feature = "full")]
pub use auth::AuthHeaders;
#[cfg(feature = "full")]
pub use auth::AuthKeyringBackendKind;
#[cfg(feature = "full")]
pub use auth::AuthManager;
#[cfg(feature = "full")]
pub use auth::AuthManagerConfig;
#[cfg(feature = "full")]
pub use auth::CLIENT_ID;
#[cfg(feature = "full")]
pub use auth::CLIENT_ID_OVERRIDE_ENV_VAR;
#[cfg(feature = "full")]
pub use auth::CODEX_ACCESS_TOKEN_ENV_VAR;
#[cfg(feature = "full")]
pub use auth::CODEX_API_KEY_ENV_VAR;
#[cfg(feature = "full")]
pub use auth::CodexAuth;
#[cfg(feature = "full")]
pub use auth::ExternalAuth;
#[cfg(feature = "full")]
pub use auth::ExternalAuthFuture;
#[cfg(feature = "full")]
pub use auth::ExternalAuthRefreshContext;
#[cfg(feature = "full")]
pub use auth::ExternalAuthRefreshReason;
#[cfg(feature = "full")]
pub use auth::OPENAI_API_KEY_ENV_VAR;
#[cfg(feature = "full")]
pub use auth::REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR;
#[cfg(feature = "full")]
pub use auth::REVOKE_TOKEN_URL_OVERRIDE_ENV_VAR;
#[cfg(feature = "full")]
pub use auth::RefreshTokenError;
#[cfg(feature = "full")]
pub use auth::UnauthorizedRecovery;
#[cfg(feature = "full")]
pub use auth::default_client;
#[cfg(feature = "full")]
pub use auth::enforce_login_restrictions;
#[cfg(feature = "full")]
pub use auth::load_auth_dot_json;
#[cfg(feature = "full")]
pub use auth::login_with_access_token;
#[cfg(feature = "full")]
pub use auth::login_with_api_key;
#[cfg(feature = "full")]
pub use auth::login_with_bedrock_api_key;
#[cfg(feature = "full")]
pub use auth::logout;
#[cfg(feature = "full")]
pub use auth::logout_with_revoke;
#[cfg(feature = "full")]
pub use auth::oauth_client_id;
#[cfg(feature = "full")]
pub use auth::read_codex_access_token_from_env;
#[cfg(feature = "full")]
pub use auth::read_openai_api_key_from_env;
#[cfg(feature = "full")]
pub use auth::save_auth;
#[cfg(feature = "full")]
pub use auth_env_telemetry::AuthEnvTelemetry;
#[cfg(feature = "full")]
pub use auth_env_telemetry::collect_auth_env_telemetry;
#[cfg(feature = "full")]
pub use outbound_proxy::AuthRouteConfig;
#[cfg(feature = "full")]
pub use token_data::TokenData;
