import Foundation

let SAND_LOG_KEY = "sand"
let TELEMETRY_DROPPED_EVENT = "sand.telemetry.dropped"
let TELEMETRY_DROP_REASONS = ["ship_failed", "overflow_evicted", "replay_expired", "backend_dropped", "account_rotated"]
let TELEMETRY_DROP_UNIT_BY_REASON = [
    "ship_failed": "attempts",
    "overflow_evicted": "entries",
    "replay_expired": "entries",
    "backend_dropped": "entries",
    "account_rotated": "entries",
]
let TELEMETRY_SHIP_TIMEOUT_EVENT = "sand.telemetry.ship_timeout"
let TURN_START_EVENT = "agent.turn.start"
let TURN_OUTCOME_EVENT = "agent.turn.outcome"
let TURN_OUTCOME_DETAIL_EVENT = "sand.turn.outcome_detail"
let TOOL_CALL_ERROR_EVENT = "sand.tool_call.error"
let TOOL_CALL_STALLED_EVENT = "sand.tool_call.stalled"
let TOOL_CALL_STARTED_EVENT = "sand.tool_call.started"
let AGENT_ERROR_EVENT = "sand.agent.error"
let AGENT_ERROR_DETAIL_EVENT = "sand.agent.error.detail"
let BOX_STORE_SYNC_EVENT = "sand.box_store_sync"
let BOX_STORE_DB_CAPTURE_EVENT = "sand.box_store_db_capture"
let BOX_STORE_MANIFEST_CONFLICT_EVENT = "sand.box_store_manifest_conflict"
let JOURNAL_OUTCOME_EVENT = "sand.journal.outcome"
let HOST_LOG_EVENT = "sand.host.log"
let BOX_LOG_EVENT = "sand.box.log"
let BOX_LOG_SHIP_EVENT = "sand.box.log_ship"
let DESKTOP_HEALTH_EVENT = "sand.box.desktop_health"
let HOST_STARTUP_EVENT = "sand.host.startup"
let HOST_LIFECYCLE_EVENT = "sand.host.lifecycle"
let HOST_EVENT_LOOP_EVENT = "sand.host.event_loop"
let MCP_AUTH_CLEANUP_EVENT = "sand.mcp_auth_cleanup"
let MCP_DISCOVERY_FAILED_EVENT = "sand.mcp.discovery_failed"
let CONNECTOR_AUTH_EVENT = "sand.connector_auth"
let SKILL_PUBLISH_EDGE_FAILED_EVENT = "sand.skill_publish.edge_failed"
let PLUGIN_SKILLS_SYNC_EVENT = "sand.plugin_skills.sync"
let TEACH_RECORDING_CAP_STOP_FAILED_EVENT = "sand.teach.cap_stop_failed"
let TEACH_RECORDING_START_FAILED_EVENT = "sand.teach.recording_start_failed"
let BOX_COPY_IN_EVENT = "sand.box_copy_in"
let INFERENCE_CREDENTIAL_RENEWAL_EVENT = "sand.inference_credential.renewal"
let DAEMON_PING_EVENT = "sand.box.daemon_ping"
let BOX_BOOT_STAGE_EVENT = "sand.box.boot_stage"
let BOX_BOOT_FAILURE_EVENT = "sand.box.boot_failure"
let EGRESS_TUNNEL_EVENT = "sand.box.egress_tunnel"
let HOST_BOOT_FETCH_EVENT = "sand.box.host_boot_fetch"
let BOX_IMAGE_CHECK_EVENT = "sand.box.image_check"
let EXEC_DAEMON_RESTART_EVENT = "sand.box.exec_daemon_restart"
let BOX_PROCESS_CRASH_EVENT = "sand.box.process_crash"
let SUPERVISOR_RESTART_EVENT = "sand.box.supervisor_restart"
let COOKIE_PERSIST_EVENT = "sand.box.cookie_persist"
let GATEWAY_COMMAND_ERROR_EVENT = "sand.gateway_command_error"
let GATEWAY_COMMAND_TIMING_EVENT = "sand.gateway_command_timing"
let AUTOMATION_LIFECYCLE_EVENT = "sand.automation.lifecycle"
let AUTOMATION_SHADOW_PRUNE_EVENT = "sand.automation.shadow_prune"
let AUTO_REVIEW_DISPLAY_RECHECK_FAILED_EVENT = "sand.auto_review.display_recheck_failed"
let AUTO_REVIEW_EXPIRE_SWEEP_FAILED_EVENT = "sand.auto_review.expire_sweep_failed"
let MCP_HOST_EDGE_FAILED_EVENT = "sand.mcp.host_edge_failed"
let HOST_CRASH_EVENT = "sand.host.crash"
let HOST_INVARIANT_VIOLATION_EVENT = "sand.host.invariant_violation"
let TURN_INTERRUPT_EVENT = "sand.turn.interrupt"
let TURN_AWAIT_EVENT = "sand.turn.await"
let TURN_RETRY_EVENT = "sand.turn.retry"
let CLOSING_SEND_NUDGE_EVENT = "sand.turn.closing_send_nudge"
let USER_MESSAGE_RECEIVED_EVENT = "sand.user_message.received"
let SUBAGENT_REVIVAL_EVENT = "sand.subagent.revival"
let SHELL_REVIVAL_EVENT = "sand.shell.revival"
let COMPUTER_USE_USAGE_EVENT = "sand.computer_use.usage"
let TTFT_EVENT = "sand.ttft"
let SEND_DISPATCH_EVENT = "sand.send_dispatch"
let QUEUE_ACCEPTED_EVENT = "sand.queue.accepted"
let QUEUE_DEQUEUED_EVENT = "sand.queue.dequeued"
let QUEUE_WATCHDOG_EVENT = "sand.queue.watchdog"
let ACK_OBLIGATION_EVENT = "sand.ack.obligation"
let PENDING_WAKE_EVENT = "sand.pending_wake"
let CHROME_SESSION_STAGE_EVENT = "sand.chrome_session_stage"
let AGENT_OPEN_EVENT = "sand.agent.open"
let HOST_UPGRADE_EVENT = "sand.host.upgrade"
let TURN_USAGE_EVENT = "sand.turn.usage"
let TURN_EMPTY_DELIVERY_EVENT = "sand.turn.empty_delivery"
let TURN_USAGE_SCHEMA_VERSION = "2"
let BOX_RECREATE_DECIDED_EVENT = "sand.box.recreate_decided"
let BOX_HELP_EVENT = "sand.box_help"
let CLIENT_RESOURCE_EVENT = "sand.client_resource"
let SESSION_STORE_DB_EVENT = "sand.session.store_db"
let SESSION_MAINTENANCE_EVENT = "sand.session.maintenance"
let SESSION_MATERIALIZE_EVENT = "sand.session.materialize"
let SESSION_SUMMARY_BUILD_EVENT = "sand.session.summary_build"
let CONVERSATION_GC_EVENT = "sand.conversation.gc"
let SEARCH_INDEX_HEALTH_EVENT = "sand.search_index.health"
let HOST_EVENT_BUS_EVENT = "sand.host.event_bus"
let BOX_STORE_DIAGNOSTIC_EVENT = "sand.box_store.diagnostic"
let AUTOMATION_CLOUD_SYNC_EVENT = "sand.automation.cloud_sync"
let MANAGED_SETUP_LOAD_FAILED_EVENT = "sand.managed_setup.load_failed"
let ATTACHMENT_READ_MISS_EVENT = "sand.attachment.read_miss"
let ACTION_AUDIT_DROP_EVENT = "sand.action_audit.drop"
let HOST_DIAGNOSTIC_EVENT = "sand.host.diagnostic"
let EXPERIMENTS_DIAGNOSTIC_EVENT = "sand.experiments.diagnostic"
let LOCAL_EXEC_REFUSED_EVENT = "sand.local_exec.refused"
let LOCAL_EXEC_FAILED_EVENT = "sand.local_exec.exec_failed"
let LOCAL_EXEC_PROVIDER_EVENT = "sand.local_exec.provider"
let MEMORY_SYNTHESIS_EVENT = "sand.memory.synthesis"
let BOT_BLOCK_EVENT = "sand.bot_block"
let BOT_BLOCK_DETAIL_EVENT = "sand.bot_block_detail"
let WEBAUTHN_PROXY_EVENT = "sand.webauthn_proxy"
let WEBAUTHN_SIGN_ERROR_CLASSES = [
    "no_credentials","pin_not_set","pin_blocked","pin_other","cancelled_or_timeout","unsupported_option",
    "hid_error","ambiguous_credential","bad_options","create_unsupported","platform_api","signer_other",
    "helper_spawn_failed","helper_no_result",
]
