import Foundation

enum IOSRPCArgumentShape: String, Equatable, Sendable {
    case none
    case object
}

enum IOSMainRPCRuntime {
    static let contractName = "main"
    static let eventFamily = "events"
    static let eventNames: [String] = [
        "box-migration",
        "cursor-auth-changed",
        "deep-link",
        "dev-box-pull-progress",
        "dev-box-rebuild",
        "egress-tunnel-changed",
        "egress-tunnel-status-changed",
        "experiments-changed",
        "focus-agent",
        "force-onboarding",
        "open-about",
        "open-feedback",
        "skip-onboarding",
        "theme-changed",
        "update-status",
        "vnc-user-presence",
        "window-state",
        "webauthn-proxy-changed",
        "zoom-factor-changed",
    ]
    static let methodTable: [String: IOSRPCArgumentShape] = [
        "openExternal": .object,
        "submitFeedback": .object,
        "getDesktopEnvironment": .none,
        "getWindowState": .none,
        "minimizeWindow": .none,
        "toggleMaximizeWindow": .none,
        "closeWindow": .none,
        "resizeWindowWidth": .object,
        "setTitleBarOverlayTone": .object,
        "getThemeState": .none,
        "setThemePreference": .object,
        "getEgressTunnelEnabled": .none,
        "setEgressTunnelEnabled": .object,
        "getEgressTunnelStatus": .none,
        "getWebauthnProxyEnabled": .none,
        "setWebauthnProxyEnabled": .object,
        "getUpdateStatus": .none,
        "checkForUpdates": .none,
        "setUpdateTrack": .object,
        "quitAndInstallUpdate": .none,
        "setAutoUpdateWhenIdleOptIn": .object,
        "getBoxMigrationStatus": .none,
        "markDeepLinksReady": .none,
        "getOnboardingSeen": .none,
        "setOnboardingSeen": .object,
        "getTimeZone": .none,
        "setTimeZoneOverride": .object,
        "getAutoReviewInstructions": .none,
        "setAutoReviewInstructions": .object,
        "getLocalToolPermission": .none,
        "getLocalToolPermissionCeiling": .none,
        "setLocalToolPermission": .object,
        "recordLocalToolApproval": .object,
        "clearLocalToolApprovals": .none,
        "getSidebarCollapsed": .none,
        "setSidebarCollapsed": .object,
        "pickAvatarSource": .none,
        "pickAvatarFile": .none,
        "generateAgentAvatarImage": .object,
        "resolveAttachmentMedia": .object,
        "readAttachmentText": .object,
        "readAttachmentBytes": .object,
        "stageAttachmentBytes": .object,
        "downloadAttachment": .object,
        "commitStagedAttachments": .object,
        "discardStagedAttachment": .object,
        "forceRecreateComputer": .none,
        "updateComputer": .object,
        "forceReconnectGateway": .none,
        "getExperimentsSnapshot": .none,
        "applyFeatureFlagOverride": .object,
        "refreshFeatureFlags": .none,
        "startRpcTraceWindow": .none,
        "getAgentDefaultModel": .none,
        "setAgentDefaultModel": .object,
        "getComputerUseModel": .none,
        "setComputerUseModel": .object,
        "getHostPinnedAgents": .none,
        "setHostPinnedAgents": .object,
        "getHostSidebarSections": .none,
        "setHostSidebarSections": .object,
        "getAvailableModels": .none,
        "getInferenceRouter": .none,
        "setInferenceRouter": .object,
        "getBoxRuntime": .none,
        "setBoxRuntime": .object,
        "transcribeAudio": .object,
        "getCursorAuthStatus": .none,
        "loginCursor": .none,
        "cancelCursorLogin": .none,
        "logoutCursor": .none,
        "updateCursorAccountName": .object,
        "getCursorAvatar": .none,
        "getCursorWeeklyUsage": .none,
        "getCursorUsageSummary": .none,
        "getCursorPrReviewPreferences": .none,
        "getCursorPrivacyModeEnabled": .none,
        "getSandAccess": .none,
        "getSandAccessFresh": .none,
        "invokeCursorDashboardAction": .object,
        "cancelCursorSandTrial": .none,
        "reportAgentLoad": .object,
        "reportAccessBlocked": .object,
        "reportAgentsUnreachable": .object,
        "reportRecoveryAction": .object,
        "reportRebuildLifecycle": .object,
        "reportReconciliation": .object,
        "reportBoxVisibility": .object,
        "reportSendLatency": .object,
        "reportSendAck": .object,
        "reportReactionAck": .object,
        "reportRenderTtfr": .object,
        "reportRenderStream": .object,
        "reportVncSession": .object,
        "reportVncLiveness": .object,
        "reportOpenComputer": .object,
        "reportUpdatePrompt": .object,
        "reportSigninGate": .object,
        "reportOnboardingStep": .object,
        "reportClientFailure": .object,
        "openCloudAgent": .object,
        "getLinkMetadata": .object,
        "listAllAutomations": .none,
        "listSecrets": .none,
        "revealSecret": .object,
        "upsertSecrets": .object,
        "removeSecrets": .object,
        "getMcpState": .none,
        "getEffectivePlugins": .none,
        "getMcpCatalog": .none,
        "getMcpTeamPopularity": .none,
        "getMcpPluginLogo": .object,
        "installEntry": .object,
        "updatePluginInstall": .object,
        "removeMcpServer": .object,
        "uninstallPlugin": .object,
        "authenticateMcpServer": .object,
        "renameMcpAccount": .object,
        "removeMcpAccount": .object,
        "setMcpCustomInstructions": .object,
        "listMcpServerTools": .object,
        "toggleMcpToolDisabled": .object,
    ]

    static func isMethod(_ name: String) -> Bool {
        methodTable[name] != nil
    }

    static func isEvent(_ name: String) -> Bool {
        eventNames.contains(name)
    }

    static func methodChannel(_ method: String) -> String {
        IOSRPCEdgeRuntime.methodChannel(edge: contractName, method: method)
    }

    static func eventChannel(_ event: String) -> String {
        IOSRPCEdgeRuntime.eventChannel(edge: contractName, event: event)
    }
}
